{
  throwOnGet();
  throw new AssertionError("Unreachable");
}
