{
  future.cancel(false);
  assertThat(future.set(3)).isFalse();
  assertThat(future.isDone()).isTrue();
  assertThat(future.isCancelled()).isTrue();
  try {
    future.get();
    fail();
  }
 catch (  CancellationException expected) {
  }
}
