{
  assertTrue(resultFuture.cancel(true));
  assertTrue(resultFuture.isCancelled());
  assertTrue(inputFuture.isCancelled());
  assertFalse(outputFuture.isCancelled());
  try {
    resultFuture.get();
    fail("Result future is cancelled and should have thrown a" + " CancellationException");
  }
 catch (  CancellationException expected) {
  }
}
