{
  Exception e=new Exception();
  CacheLoader<Object,Object> loader=exceptionLoader(e);
  LoadingCache<Object,Object> cache=CacheBuilder.newBuilder().recordStats().build(loader);
  CacheStats stats=cache.stats();
  assertEquals(0,stats.missCount());
  assertEquals(0,stats.loadSuccessCount());
  assertEquals(0,stats.loadExceptionCount());
  assertEquals(0,stats.hitCount());
  try {
    cache.get(new Object());
    fail();
  }
 catch (  ExecutionException expected) {
    assertSame(e,expected.getCause());
  }
  stats=cache.stats();
  assertEquals(1,stats.missCount());
  assertEquals(0,stats.loadSuccessCount());
  assertEquals(1,stats.loadExceptionCount());
  assertEquals(0,stats.hitCount());
  try {
    cache.getUnchecked(new Object());
    fail();
  }
 catch (  UncheckedExecutionException expected) {
    assertSame(e,expected.getCause());
  }
  stats=cache.stats();
  assertEquals(2,stats.missCount());
  assertEquals(0,stats.loadSuccessCount());
  assertEquals(2,stats.loadExceptionCount());
  assertEquals(0,stats.hitCount());
  cache.refresh(new Object());
  checkLoggedCause(e);
  stats=cache.stats();
  assertEquals(2,stats.missCount());
  assertEquals(0,stats.loadSuccessCount());
  assertEquals(3,stats.loadExceptionCount());
  assertEquals(0,stats.hitCount());
  Exception callableException=new Exception();
  try {
    cache.get(new Object(),throwing(callableException));
    fail();
  }
 catch (  ExecutionException expected) {
    assertSame(callableException,expected.getCause());
  }
  stats=cache.stats();
  assertEquals(3,stats.missCount());
  assertEquals(0,stats.loadSuccessCount());
  assertEquals(4,stats.loadExceptionCount());
  assertEquals(0,stats.hitCount());
  try {
    cache.getAll(asList(new Object()));
    fail();
  }
 catch (  ExecutionException expected) {
    assertSame(e,expected.getCause());
  }
  stats=cache.stats();
  assertEquals(4,stats.missCount());
  assertEquals(0,stats.loadSuccessCount());
  assertEquals(5,stats.loadExceptionCount());
  assertEquals(0,stats.hitCount());
}
